### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by AIO-Develope** [alexdhg/tiktok-printer-live#2]
i dont get any live infos it just says welcome 🥳 
![image](https://user-images.githubusercontent.com/69240351/184123166-9ead4a04-df4c-4b3f-b2ca-85f787655183.png)
![image](https://user-images.githubusercontent.com/69240351/184123205-dff85c59-0841-412c-880e-9173390d1742.png)

**Comment by tekkitlx** [comment]
same goes for me! Any solution found?
